Add bip.sh
publicsuffix/list pull request #1098
Opened 2020-09-10 21:58 UTC by joelkennedy

* [X] Description of Organization
* [X] Reason for PSL Inclusion
* [X] DNS verification via dig
* [X] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://bip.sh

Bip is a static web hosting provider. Customers are provisioned a subdomain of bip.sh to host their website on.

Reason for PSL Inclusion
====

Bip customers are provided with a subdomain of bip.sh to host their website on. These subdomains are controlled by different customers, so inclusion in this list will restrict cookie sharing between them.

DNS Verification via dig
=======

```
dig +short TXT _psl.bip.sh
"https://github.com/publicsuffix/list/pull/1098"
```

make test
=========

Local tests have passed.

2020-09-23 06:57 UTC, dnsguru requested changes
@joelkennedy can you move your section lower in the file - while you placed it alphabetically, you did so within the section submitted by centralnic.

2020-09-23 09:37 UTC, joelkennedy commented
@dnsguru apologies. I've now moved this lower in the file, let me know if this is an OK position.

2020-09-30 08:44 UTC, dnsguru approved these changes
Rationale ok
No Conflicts with Base
DNS Validation confirms
Tests ok

Approved

2020-09-30 08:44 UTC, dnsguru commented
Thank you for moving this section and re-submitting.

2020-09-30 08:44 UTC, merged

2024-07-24 00:23 UTC, groundcat commented
@joelkennedy Do you still need this entry in the PSL? It seems that Bip Service has closed down. If the project has been decommissioned and is no longer associated with an active project as described in your original request, please confirm in #2063 that it can be safely removed from the PSL to avoid leaving unnecessary debris for PSL volunteers and future registrants to deal with (#1996). Thank you.