Add wapblog's domain
publicsuffix/list pull request #1111
Opened 2020-09-30 22:43 UTC by fsodic

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

Description of Organization
====
Organization Website: https://www.wapblog.id

I'm Fajar Sodik from WapBlog Developer Team
WapBlog.ID is a platform for create a blog.

Reason for PSL Inclusion
====
WapBlog.ID is a platform blog builder who user can create a blog which our subdomain or their own domain. If they don't have a domain, we provide some excelent domain for them like wbq.me or wblog.id and many other.

It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and wapblog.id services too.

DNS Verification via dig
=======

make test
=========

2020-10-01 10:24 UTC, fsodic commented
@dnsguru is this valid bro?

2020-10-01 21:48 UTC, dnsguru requested changes
thank you for submitting through the appropriate process.  
please revise this to sort them by TLD then by SLD

2020-10-01 22:46 UTC, fsodic commented
### ****

> thank you for submitting through the appropriate process.
> please revise this to sort them by TLD then by SLD

is this about com, net, and next .id and .me?

2020-10-02 00:35 UTC, dnsguru commented on public_suffix_list.dat
> +fastblog.net
move fastblog.net to end

2020-10-02 00:58 UTC, fsodic commented on public_suffix_list.dat
> +fastblog.net
okay, it's done

2020-10-02 01:00 UTC, fsodic commented
oh i know,
.com, .id, .me, .net
order on tld extension

2020-10-05 20:29 UTC, fsodic commented
@sleevi & @dnsguru is my PR valid?

2020-10-07 22:15 UTC, fsodic reviewed
fastblog.net was moved to end

2020-10-08 23:03 UTC, dnsguru approved these changes
- No conflict with base
- DNS validations all present and accurate - domains verified
- Tests pass
- Appropriate and complete rationale

**APPROVED**

This precedes #1116 requirements on proving renewal terms >2y, but @fsodic do be aware later automation review may remove names with <1year from review left in their term (counted from the date of automation run) in the future.

2020-10-08 23:06 UTC, dnsguru commented
@fsodic thank you for revising the order of the change ; this has been reviewed and approved.  

The timing of this submission is before the 2y requirement so it will not be enforced here, but as mentioned in the approval.  There is likely to be culling automation that would use the expiry date of domains as determination, so it is wise to ensure renewing names so that automation won't pull names out.

2020-10-08 23:06 UTC, merged

2020-11-08 00:53 UTC, fsodic commented
@dnsguru I made a mistake writing a domain name, where I asked bloger.id for this PR but I included bloghp.id.
Can I change it?