Adds *.gateway.dev
publicsuffix/list pull request #1117
Opened 2020-10-08 12:06 UTC by tomboc

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://cloud.google.com/api-gateway

Engineer at Google on the Cloud API Gateway team.
====

Cloud API Gateway hosts fully managed HTTP and gRPC proxies with API policy enforcement features for GCP customers. The proxies receive a default hostname `<gateway ID>.<region code>.gateway.dev`

Our customers are not related to each other and there is no mutual trust between the gateways. By adding an entry to the public suffix list we'd like to prevent our customers from setting cookies on each `<region code>.gateway.dev` subdomain. Our use case is similar to `*.r.appspot.com` already included in the list.

DNS Verification via dig
=======

make test
=========

2020-10-08 22:33 UTC, fsodic reviewed
This domain not match new rule where domain must active at least 2 years ahead
@dnsguru

2020-10-08 22:33 UTC, fsodic commented on public_suffix_list.dat
> +*.gateway.dev
Registry Expiry Date: 2021-05-28

2020-10-08 22:46 UTC, dnsguru commented
> This domain not match new rule where domain must active at least 2 years ahead
> @dnsguru

```
 nslookup -type=txt _psl.gateway.dev
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
*** Can't find _psl.gateway.dev: No answer
```

Nor have the authority records been placed into the DNS, so it appears this is in-progress, so it will be reviewed at a point in the future.

2020-10-09 00:08 UTC, dnsguru requested changes
@tomboc talk to @sleevi pls ;
For the section you are updating, we have been requesting that the entries be sorted by TLD then SLD within, so there's some housekeeping within that section and ordering to manage.  Can you review this with the listed maintainer of that section and order this with the sorting method of TLD then SLD within those, (pardon the pun) Alphabetically.

2020-10-09 08:25 UTC, dnsguru commented
This will now require a re-base @tomboc due to #1120, and thank you for organizing the section

2020-10-12 18:33 UTC, dnsguru commented
@tomboc can you rebase using the .dat file from after the changes submitted in #1126 to reflect the updated TLD list from ICANN?

2020-10-13 10:48 UTC, tomboc commented
Thanks for all the comments.
I've rebased the branch to the current HEAD, as of writing there are no conflicts. DNS change took a bit to roll out, but now I can run the `dig` command with expected result. The domain has been renewed and will not expire until 2023-05-28.

2020-10-13 13:56 UTC, merged