Update the existing Names.of.London Public List
publicsuffix/list pull request #1146
Opened 2020-11-06 12:14 UTC by james-stevens

* [ X] Description of Organization
* [ X] Reason for PSL Inclusion
* [X ] DNS verification via dig
* [X ] Run Syntax Checker (make test)

* [ X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: https://Names.of.London/

"Names.of.London" is a business registering second level domains, mostly in new-GTLDs
In some ways similar to the old CentralNIC model (uk.com etc), but in newGTLDs

Reason for PSL Inclusion
====

Sub-Domains can be owned & operated by independent legal entities.

Existing domains are already listed, this pull-request updates the list to remove domains no longer relevant and add ones that are going to be kept & operated long term.

DNS Verification via dig
=======

"_psl" records all exist for our original inclusion, but need updating when I know the pull request number.

make test
=========

make test run & passed

2020-11-06 16:31 UTC, dnsguru commented
Updates #543 
Updater = Submitter

2020-11-06 16:36 UTC, dnsguru commented
@Names-of-London = @james-stevens - verified same submitting party despite separate account.

Please @james-stevens only need to add the _psl txt record of the PR to those added (if you have not already) names:

- from.work
- from.marketing
- with.marketing
- repair.men
- under.one
- that.win

2020-11-06 16:44 UTC, dnsguru requested changes
@james-stevens pardon the pedantic request, but please sort these alpha by TLD then SLD.

Have reviewed the following:
- DNS Check Validates Administrative oversight of added names
- Updater=Submitter (same person, different account, verified) on removed names

2020-11-06 17:09 UTC, james-stevens commented
Sort order updated - apologies, I had forgotten.

2020-11-07 00:39 UTC, dnsguru approved these changes
- DNS Validated 
- Removals : Submitter = Revising Party (validated)
- No Conflict with base
- Tests Pass
- Rationale ok

**APPROVED**

2020-11-07 00:40 UTC, merged