Added fireweb.app to PSL
publicsuffix/list pull request #1181
Opened 2021-01-11 03:47 UTC by abumusamq

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Firewebkit is tools and services available to develop the website.

Reason for PSL Inclusion
====
Firewebkit provides free domains for the developers looking to quickly setup something (which is this fireweb.app)

DNS Verification via dig
=======

make test
=========

2021-01-11 04:07 UTC, dnsguru requested changes
Please place this higher in the file - alphabetically by org name in the comment - so up in the "F's"

2021-01-11 04:58 UTC, abumusamq commented
> Please place this higher in the file - alphabetically by org name in the comment - so up in the "F's"

Done. Thanks for the review @dnsguru

2021-01-14 07:57 UTC, dnsguru approved these changes
Thank you for sorting and revising

- description accepted
- test passes
- no conflict with base
- dns authentication ok

**APPROVE**

2021-01-14 07:57 UTC, merged

2024-07-24 03:34 UTC, groundcat commented
@abumq Do you still need this entry in the PSL? The domain `fireweb.app` you requested to be added had expired and was possibly registered by a different registrant at `2023-07-30T21:51:15Z`, if it wasn't your organization re-registering the domain after it expired.

If the domain has been decommissioned and is no longer associated with an active project as described in your original request, please confirm that it can be safely removed from the PSL. If so, kindly submit a new PR to roll it back to avoid leaving unnecessary debris for PSL volunteers and future registrants to deal with (#1996). Thank you.

```
Domain Name: fireweb.app
Registry Domain ID: DFAB3EA46-APP
Registrar WHOIS Server: whois.nic.google
Registrar URL: http://www.tucows.com/
Updated Date: 2024-07-18T23:26:48Z
Creation Date: 2023-07-30T21:51:15Z
Registry Expiry Date: 2029-07-30T21:51:15Z
Registrar: Tucows Domains Inc
Registrar IANA ID: 69
Registrar Abuse Contact Email: [domainabuse@tucows.com](mailto:domainabuse@tucows.com)
Registrar Abuse Contact Phone: +1.4165350123
Domain Status: clientTransferProhibited
```

However, the new registrant added the `_psl` TXT record pointing to this PR. Could you please confirm whether it was your organization re-registering the domain after it expired and if you wish to continue including it in the PSL?

```
dig +short TXT _psl.fireweb.app
"https://github.com/publicsuffix/list/pull/1181"
```

2024-09-03 08:45 UTC, groundcat commented
@abumq This is a second notice regarding the domain fireweb.app. It was flagged that the project or organization associated with your domain may potentially no longer be active. If we don't hear back from you, your domain could be removed from the Public Suffix List (PSL).

If the service has been decommissioned and the domain is no longer linked to an active project as outlined in your original request, please reply to confirm whether it can be safely removed from the PSL. This will help avoid leaving unnecessary debris for PSL volunteers and future registrants. If your project or organization is still active, please let us know as well.

Thank you for your attention to this matter. 

---
Attempted to contact the submitter via GitHub on July 23, 2024, but no response was received.

An inquiry email has been sent to the submitter's email addresses on September 3, 2024.

cc @wdhdev

2024-09-03 23:35 UTC, groundcat commented
The email address of the initial submitter is invalid.

```
<mqureshi@amrayn.com>: host route1.mx.cloudflare.net[162.159.205.13] said: 550
5.1.1 Address does not exist. jsaXKlBJoYOE (in reply to RCPT TO command)
```

Will create a removal PR for it.