Add tenant domain to psl
publicsuffix/list pull request #1252
Opened 2021-03-29 19:27 UTC by roderickparr

* [ ] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

2021-03-29 19:43 UTC, roderickparr commented
I submitted all the prerequisites in the initial PR to add forgeblocks.com.

2021-03-29 20:16 UTC, dnsguru commented
Updates #1238

2021-03-29 20:29 UTC, dnsguru commented
Please give a rationale on this...  
I see also #1251 - while this PR extends and updates the info submitted in the original #1238, please at least provide a rationale for this individual update - why is there a new domain being added.   We want each PR to stand on their own without hunting/searching for the references

2021-03-29 22:01 UTC, roderickparr commented
The id.forgerock.io domain is our tenant domain.  This is the domain where our customer tenants reside and we issue subdomains ie widgets.id.forgerock.io. Browsers should treat each subdomain of id.forgerock.io (and forgeblocks.com) as completely separate websites.

2021-03-29 22:10 UTC, dnsguru requested changes
Please remove trailing whitespace at EOL

2021-03-29 22:30 UTC, roderickparr commented
removed trailing whitespace

2021-03-30 00:51 UTC, dnsguru approved these changes
Approved - extends #1238 ; same submitter = prior

2021-03-30 00:51 UTC, merged

2021-03-30 00:51 UTC, dnsguru commented
Thanks @roderickparr and pardon the pedantia

2021-03-30 00:56 UTC, roderickparr commented
All good