Add rs.ba suffix
publicsuffix/list pull request #1365
Opened 2021-06-28 16:03 UTC by kormang

Subdomain rs.ba, is domain for Republic of Srpska entity (part of Bosnia and Herzegovina). Applications for domain registrations are submitted through [form](http://urc.rs/index.php/domen) on  web site of Computer Center of University of Banja Luka, or by writing email to domeni@unibl.org (which belongs to University's official site).

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

Description of Organization
====

Organization Website: https://unibl.org and also http://urc.rs/index.php/page/301.
Please see **Extra info** and **Reason for PSL Inclusion** for more information.

Reason for PSL Inclusion
====

Different sites, ranging from government to private companies, use .rs.ba domain, which refers to Republic of Srpska, authonomous region of Bosnia and Hercegovina. This affects cookie policy, and how browsers treat these domains in general.

DNS Verification via dig
=======
```
$ dig +short TXT _psl.rs.ba
"https://github.com/publicsuffix/list/pull/1289"
```

make test
=========

I ran the test, and got:
```
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

Extra info
====

More info on university's computer center web site: http://urc.rs/index.php/page/301 (in Serbian language).

Political background:
Banja Luka is the capital of Republic of Srpska. Biggest university in the entity is University of Banja Luka.
Republic of Srpska is part of Bosnia and Hercegovina, with certain authonomy and close relations with Serbia (thus Computer Center of University of Banja Luka has .rs domain).

2021-06-28 16:06 UTC, kormang commented
The original PR is here: https://github.com/publicsuffix/list/pull/1289
I'm not sure if I'm supposed to open new one, or the original should be reopened (which I can't do, or at least GitHub's interface is not very intuitive).

2021-06-28 23:20 UTC, dnsguru requested changes
To proceed, this must be located in the ## Private section of the PSL, please move the submitted change out of the ICANN section, and place it within the PRIVATE section, sorted by the Organization name in the comment field.

2021-06-30 15:19 UTC, dnsguru commented
@kormang this can't be added where you located it in the change - it needs to be moved to the private section of the PSL

2021-07-01 13:35 UTC, kormang commented
Oh, sorry, I've made PR from wrong branch.

2021-07-01 13:35 UTC, closed without merging