Organize Amazon Domains
publicsuffix/list pull request #1460
Opened 2021-10-16 16:22 UTC by sleevi

Amazon has historically added their domains as per-product domains, inconsistent with other PSL participants.

This groups Amazon domains within one section. This trades the per-product separation, which has benefits, into a better reflection of the number of domains Amazon has, as well as the issues that can arise with the structure of those domains.

2021-10-16 16:22 UTC, sleevi commented
@dnsguru Curious your thoughts here, given https://github.com/publicsuffix/list/pull/1403 and https://github.com/publicsuffix/list/pull/1404

2021-10-18 21:46 UTC, dnsguru requested changes
Should preserve 'sections' per group, to preserve maintainers (see centralnic) and also sorting should to be A-Z Asc by

- TLD
- SLD
- 3LD
- 4LD

2021-11-18 20:41 UTC, plygrnd commented
@sleevi Checkin' in from AWS (I'm on the Security Ops team). Been following some of the discussions around our PSL submissions (#1422 , #1404 , others) and I understand you (and the other maintainers) are concerned about how much we're expanding the list. Let me know how I can help, please.

2021-11-19 08:35 UTC, dnsguru commented
@plygrnd Thank you for popping in.   We are volunteers on this project so we're not looking to enroll for a lot of coordinations or calls, so a light touch is appreciated.

There are a LOT of requests coming from Amazon - from a few different sides - sometimes contractors, sometimes employees - we really don't know the difference and use the DNS _PSL validation to determine authority/administrative control over a name.

Off the top of my head It would be helpful to have 

 - a more holistic interaction (perhaps a sole / central contributor / sole source) 
 - more of an extreme bias on file-size modesty - the regional DC stuff is nobueno for this
 - sorting of the requested entries as I describe above (following the guidelines)

2021-11-19 14:30 UTC, plygrnd commented
@dnsguru thank _you_ for popping in - good points. Will maintain a lightweight presence. 

Think the first step is a list of open/rejected submissions from Amazon. If you or another volunteer can help me collate these that'd help greatly. 

For my part, I'll discuss 

> sole / central contributor / sole source

internally and get back to you. As @erichays mentioned in #1422, some of our services won't do well with wildcard submissions, or won't work at all. We'll need to figure something out for these or leave them alone. 

I am happy to work with @sleevi to sort the list per your comment above - Ryan please let me know how you'd like to manage this.

2022-01-20 21:34 UTC, dnsguru commented
Checking in on this @plygrnd - noticing that there are new requests coming in from different projects within Amazon and we have a fairly decent backlog here of Amazon requests that likely need attention that I consider this particular PR as a gate on.

@sleevi has identified a reduced participation and much earned sebbatical 

I think the objective here is one central voice from Amazon on their submissions, and those submissions following as modest a footprint as possible (ie fewer=better) on filesize in the private section.

2022-01-20 21:46 UTC, dnsguru commented
> @dnsguru I'm not sure I understand your remark re: sections per group. The goal is to eliminate that, especially as we see there is a lack of central maintenance. I think the CentralNic should also be fixed, if these are the same entity.
> 
> Did I misunderstand?

For Centralnic, they appear to be a central coordinator for those strings under them, which they in turn identify subsections for, including those that are exiting their service.

The structure of those would have the subsections be ascending a-z sorted within parentco section
```
//Company  URL
//Subsection 1
//Submitter EMAIL
[domains in ascending order by TLD,SLD,3LD,4LD]

//Subsection 2
//Submitter EMAIL
[domains in ascending order by TLD,SLD,3LD,4LD]
```
as a comedic abstract:

```
// MAINCO https://mainco.example
// Mainco Bronco Training Division
// Submitted by "Newguy Deerheadlights" <ohno@first.rodeo>
first.rodeo
trampledby.horse

// Mainco Synthetic Pants and Zirconia Division
// Submitted by "Fancy Dancer" <rythmrug@toomuch.cologne>
jerseyshore.toomuch.cologne
miamisouthbeach.toomuch.cologne
bellbottom.diy.fashion
goldchain.hot.fashion

```

2022-01-21 20:56 UTC, plygrnd commented
> Checking in on this @plygrnd - noticing that there are new requests coming in from different projects within Amazon and we have a fairly decent backlog here of Amazon requests that likely need attention that I consider this particular PR as a gate on.
> 
> @sleevi has identified a reduced participation and much earned sebbatical
> 
> I think the objective here is one central voice from Amazon on their submissions, and those submissions following as modest a footprint as possible (ie fewer=better) on filesize in the private section.

@dnsguru Thanks for letting me know that Ryan's taking some time off. We're making progress:

1.  We will centralize our updates via an AWS-owned [fork of the PSL](https://github.com/aws/public-suffix-list). 
2. These updates will be batched and reviewed by a core team within Amazon to ensure that they conform to the PSL standards (size, syntax, completeness, relevance, scope)
3. We will submit these updates once they pass our internal review.

My team and I need some information to continue working on this process:

1. How frequently would you prefer us to submit PRs? Will two PRs/month work?
2. How would you prefer the updates within each PR to be structured? To us, it makes sense to batch updates by AWS service (one service, many geographic regions). Alternatively, we can batch updates by AWS region (one region, multiple services). 

Finally, if you have a list of pending updates for Amazon, please let me know. I'd like to ensure that I'm tracking everything we have in the queue.

2022-01-27 20:21 UTC, dnsguru commented
> list of pending updates for Amazon

Looks like: 

- #1403 
- #1404
- #1422
- #1424 

But in Amazon's self-interest can you hunt for more in case this volunteer missed any?

2022-01-27 20:33 UTC, plygrnd commented
Yep, I've been doing so - those were the four I was missing. Thank you!

On Thu, Jan 27, 2022, at 15:21, Jothan Frakes wrote:
> 
> 
>> list of pending updates for Amazon
>> 
> Looks like:
> 
>  * #1403 <https://github.com/publicsuffix/list/pull/1403>
>  * #1404 <https://github.com/publicsuffix/list/pull/1404>
>  * #1422 <https://github.com/publicsuffix/list/pull/1422>
>  * #1424 <https://github.com/publicsuffix/list/pull/1424>
> But in Amazon's self-interest can you hunt for more in case this volunteer missed any?
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/publicsuffix/list/pull/1460#issuecomment-1023606553>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFCPBBHUD5TQOLXT5PLXO4TUYGSNNANCNFSM5GDZOVTA>.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>

2022-02-09 17:51 UTC, dnsguru commented
There's a large number of PR here to wrangle / close or merge as I apply unpaid cycles towards this queue that I'd like to move from `not done` to `done`, and there are likely a large number of internal constituents for you @plygrnd, is there any new information or news on this PR?

2022-02-22 17:15 UTC, plygrnd commented
@dnsguru 

I've gone through the list of open PRs again. Noted that #1504 also belongs to Amazon. I've notified the Amazon owners of each open PR that we plan to close them shortly, and use a new (centralized, semi-automated) process to manage Amazon's PSL submissions. I plan to close these PRs by next week or sooner.

2022-03-07 20:54 UTC, dnsguru commented
@plygrnd I had some volunteer cycles briefly this afternoon to review the pending PRs queue and saw this is still open.  There are a number of semi-done requests as noted.  Has this evolved within Amazon at all?  The cumulative pull requests of Amazon/AWS et al are stalled in the meantime.  As you [mentioned above](https://github.com/publicsuffix/list/pull/1460#issuecomment-1018853222) that Amazon is going to maintain a local PSL fork, should we close out the stale PRs here from Amazon et al and watch for the consolidated/curated contribution?

If there ends up being a link for that or group to work with, we could add a 'if you work for amazon submit your changes here' with a link or email address to ensure we don't end up with more build-up debris fields here of stuff that could/should be routing through your sieve.

2022-07-15 18:42 UTC, aph3rson commented
@dnsguru - Thanks for your patience in working with us. @plygrnd is taking a step back from the project on our side, so I'll be your primary point of contact (feel free to email the email address you may have used prior to confirm this).

-----

> As you https://github.com/publicsuffix/list/pull/1460#issuecomment-1018853222 that Amazon is going to maintain a local PSL fork, should we close out the stale PRs here from Amazon et al and watch for the consolidated/curated contribution?

We do intend to maintain a local PSL fork (in an AWS-owned repository) purely for coordination purposes, and file PRs back to yours as we aggregate the submissions internally. Our team maintains the permissions on this repository, and it is clearly AWS-owned as it's in our GitHub organization. We hope that this solves issues related to attribution of AWS-owned suffixes in the PR process.  
We'll be handling the aggregation via draft PRs, which we internally disseminate to teams as we aggregate their new suffixes for eventual inclusion. Here's an example: #1590 - we have teams with pending changes that we'll be distributing this to as we incorporate their suffixes/get their DNS challenges configured.

-----

> We could add a 'if you work for amazon submit your changes here' with a link or email address

We've internally vended the guidance on how to submit PSL changes to our team - these PSL changes were initially driven by other team members, so the single-threaded guidance on our side should resolve this. Feel free to close PRs for AWS domains which are not submitted through this process/the aforementioned repository - the ones mentioned in this ticket have already been contacted internally about this new process.

-----

With regards to reorganization of Amazon domains (i.e. the actual issue this is related to), we prefer more the CentralNic model described [here](https://github.com/publicsuffix/list/pull/1460#issuecomment-1017955653) - this is more in-line with how we manage these teams/their suffixes internally. We may also add a short internal identifier to the "subsection" heading to further correlate suffixes on our side - this would be for our use, and would not have any impact on the list itself. We will work to reorganize the list in this fashion, but it likely would be in a different PR.

-----

Lastly, I appreciate y'all's efforts in working with us on this. We're aiming to maintain a light presence, and not gum up your processes too much, and limit our suffixes on the PSL to only that which are required. If there are any concerns with the processes we're using, feel free to reach out to us out-of-band.

2022-10-11 15:51 UTC, dnsguru commented
Spoke with @aph3rson irl, there will be a review of these to determine proceeding or incorporating into next on-cadence holistic aws update.

2022-10-11 20:43 UTC, aph3rson commented
@dnsguru Working on actioning this now, one question. When implementing the so-called CentralNic model described [above](https://github.com/publicsuffix/list/pull/1460#issuecomment-1017955653), no trailer is specified.

Do you feel one is warranted? A format I could see is a single line of `// end`, followed by whitespace, followed by the exact company name from the company header. Building off your abstract, that might look like the following:

```txt

// MAINCO https://mainco.example
// Mainco Bronco Training Division
// Submitted by "Newguy Deerheadlights" <ohno@first.rodeo>
trampledby.horse
first.rodeo

// Mainco Synthetic Pants and Zirconia Division
// Submitted by "Fancy Dancer" <rythmrug@toomuch.cologne>
jerseyshore.toomuch.cologne
miamisouthbeach.toomuch.cologne
bellbottom.diy.fashion
goldchain.hot.fashion

// end MAINCO
```

2022-10-11 20:49 UTC, dnsguru commented
Could you use "concludes" instead of "end"? - concerned that folks may have built parsers that trigger on "end".  Otherwise, good

2022-10-13 19:34 UTC, aph3rson commented
@dnsguru I submitted #1629, which should capture all the reorganization efforts we discussed prior.

As we continue adding more records, we'll be sure to limit them to this section of the PSL only.

2022-10-14 14:15 UTC, dnsguru commented
This is addressed by #1629 ; closing

2022-10-14 14:15 UTC, closed without merging