Add ktistory.com
publicsuffix/list pull request #1493
Opened 2021-12-24 06:40 UTC by Shystorm

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)
* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
* [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
* [x] This request was _not_ submitted with the objective of working around other third-party limits
* [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
* [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting
---
* [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---
Description of Organization
====

Organization Website: https://www.kakaocorp.com/page/?lang=ENG&tab=all

We are Kakao who provides all online services such as mobile messenger, search, and blog in Korea.
(https://www.kakaocorp.com/page/service/service)

Among them, this request is for the following blog service:
(https://www.tistory.com/)

Reason for PSL Inclusion
====
tistory is a blog service. 
Many users use subdomains of tistory.com to serve individual blog with advertisements together. 
All users who use tistory.com are being sanctioned by a single user's violation of the advertising policy. 
So we add the domain to PSL to enforce cookie policy and to apply advertising policy for each individual subdomain.

ktistory.com is a domain to check the service impact before implementing the above. If there is no problem with the service through this verification, tistory.com will also be added.

Also, the expiry date of the domain is more than two years away, and I will also keep the domain and _psl. 
Domain Expiration Date: 2025-12-07

DNS Verification via dig
=======
dig +short TXT _psl.ktistory.com

make test
=========
I've run make test and I can confirm everything passes.

2021-12-24 08:29 UTC, dnsguru commented
@Shystorm - JaeYoong 
Can you please add more description of the company and the website?

Can you also confirm that I understand the request correctly?  It seems that for users that do not opt to use a custom domain of their own, your service will allow them to use a subdomain of tistory.com, and there are some who abuse this kindness that are making consequences for the entire domain space.  **Is this correct?**

Is this request going to come back to us to also include tistory.com once you test ktistory.com?  If so, is it possible to do these together all at once?  We are volunteer-based and that is much more time-efficient to do all at once.

2021-12-24 16:48 UTC, Shystorm commented
> @Shystorm - JaeYoong Can you please add more description of the company and the website?
> 
> Can you also confirm that I understand the request correctly? It seems that for users that do not opt to use a custom domain of their own, your service will allow them to use a subdomain of tistory.com, and there are some who abuse this kindness that are making consequences for the entire domain space. **Is this correct?**
> 
> Is this request going to come back to us to also include tistory.com once you test ktistory.com? If so, is it possible to do these together all at once? We are volunteer-based and that is much more time-efficient to do all at once.

First of all, I'm sorry that I wrote the reason for the request so vaguely.
I supplemented the "Description of Organization" and "Reason for PSL Inclusion" sections a bit more.  To help you understand, I have written a little more real example.

I would like to request two domains at once to minimize your work, but we need verification before that.
We want to clearly check the impact of the cookie policy and service that will be changed due to the application of the PSL. This test period will not be short, and we will request again after sufficient verification.

I ask for your understanding that it will be proceeded with two requests.

2021-12-25 10:04 UTC, dnsguru commented
Thank you for the more full description - the requests and dialog become the public record for requests, so this is helpful for the other volunteers and community to see.

>I ask for your understanding that it will be proceeded with two requests.

OK and I understand.  1 or 2 entries is modest.  It sounds like the approach being taken is to be careful to set up an alternative name to test the result on a non-production befire you would request the production domain, so that there is not disruption to your users.

This is a conservative approach.   Please understand that different browsers include PSL updates at different pace of update and schedule, and the volunteers here have no ability to control that.

2021-12-25 14:57 UTC, Shystorm commented
@dnsguru 
Everything you mentioned is correct.
I also understand that browsers have different update schedules.
Thanks for the explanation.
Please let me know if there is any further action I need to take.

Always grateful for your voluntary work.

2022-02-22 21:48 UTC, dnsguru requested changes
Hi @Shystorm - please re-base this PR as it collided with another that was merged in between when you took the public_suffix_list.dat file to edit.

2022-02-23 05:52 UTC, Shystorm commented
@dnsguru 

Unnecessary commits were made while rebase was in progress.
- b01fb45
- b4e5874
- eea5a6d

First, the reorder was performed as above , not rebase.
If necessary, I will deal with the issue as a new PR.

2022-02-25 06:49 UTC, Shystorm commented
@dnsguru 
I completed the order correction of Kapsi and Kakao and also completed the rebase.
Please review it again.

2022-02-25 07:05 UTC, dnsguru commented
Hi @Shystorm thank you for taking that extra step and apologies that you needed to.   Merging now.

2022-02-25 07:06 UTC, dnsguru approved these changes
- Domain Validated
- Guidelines Followed
- Tests Pass
- No Conflict with Base

APPROVED

2022-02-25 07:06 UTC, merged

2024-09-18 06:25 UTC, groundcat commented
Hello @Shystorm , it seems that the project or organization associated with your domain, which was merged into the Public Suffix List (PSL), may no longer be active based on the observable usage of subdomains. 

- ktistory.com SERVFAIL error

If the service has been decommissioned and the domain is no longer linked to an active project, as outlined in your original request, please confirm whether it can be safely removed from the PSL. This will help prevent leaving unnecessary entries for PSL volunteers and future registrants, as requesters often "set and forget" and neglect to request the removal of their domains from the PSL when their project reaches its end of life (EOL).

The PSL is a globally used resource, and it's important to understand that tens of millions, if not hundreds of millions, of devices and users incorporate the list. We aim to keep it as minimal as possible for those who truly need PSL inclusion. Projects that are smaller in scale, such as those without thousands of users or subdomains belonging to thousands of individual entities, will likely be ineligible for inclusion. If you no longer need your entry to remain on the PSL, **please create a new pull request to remove it** or reply here to confirm.

If your project or organization is still active and requires continued inclusion in the PSL, please reply at your earliest convenience. If we do not hear back from you for an extended period, **your entry may be subject to removal**. 

Additionally, ensure that the required `_psl` TXT record is maintained, as specified in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines#validation-of-submissions--always), and that your domain is kept renewed with an expiry date of more than 2 years at all times to avoid future removal.

Thank you.