Add vn.al
publicsuffix/list pull request #1539
Opened 2022-03-18 03:19 UTC by vnddns

* [x] Description of Organization
* [x] Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 
  * [x] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [x] This request was _not_ submitted with the objective of working around other third party limits
  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the guidelines.
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your 
core domain name in ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate the PSL do what they do, and when.
It is not within the PSL volunteers' control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken 
it will stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] Yes, I understand.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  Proceed.
---

Description of Organization
====

Organization Website: https://vn.al
This is a Dynamic DNS service provider.

Reason for PSL Inclusion
====

This is dynamic dns service, which means subdomains are registered by independent 3rd parties. It's important to treat them separately for cookie security reasons.
Also, the expiry date of the domain is more than two years away, and I will also keep the domain and _psl.

DNS Verification via dig
=======

```
dig +short TXT _psl.vn.al
"https://github.com/publicsuffix/list/pull/1539"
```
make test
=======
```
Test completed successfully.
```

2022-03-24 05:08 UTC, vnddns commented
I have updated the "Description of Organization" & "Reason for PSL Inclusion" & fix sorting @dnsguru

2022-03-30 08:18 UTC, dnsguru requested changes
Please read the guidelines about placement and sorting - do not put this at the EOF

2022-03-30 09:44 UTC, vnddns commented
Thanks for your patience and time, I have corrected what was missing. If you think some details are still missing or incorrect, please let me know. Thank you again !!!

2022-09-27 03:01 UTC, vnddns commented
Hello @dnsguru . Is there anything missing from this PR ?

2023-09-05 06:23 UTC, danderson commented
(just a passing volunteer reviewing the backlog)

vn.al no longer resolves, neither the homepage nor the `_psl.vn.al` verification record. The domain is still registered (can't get details, .AL doesn't provide whois service), but vn.al's two nameservers are both offline.

Digging a little deeper, the IPs of vn.al's nameservers aren't even being advertised on the internet right now. For example, Hurricane Electric's looking glass:

```
core2.abq1.he.net> show ip bgp routes detail 66.59.198.225 
  BGP4 : None of the BGP4 routes match the display condition
```

Cogent's looking glass:

```
Tue Sep  5 06:14:59.399 UTC
% Network not in table
```

Without further information, it seems to me the project/organization is defunct, and this PR can be closed as obsolete.

2023-09-05 06:40 UTC, dnsguru commented
> (just a passing volunteer reviewing the backlog)

thx @danderson 
 
> vn.al no longer resolves, neither the homepage nor the `_psl.vn.al` verification record. The domain is still registered (can't get details, .AL doesn't provide whois service), but vn.al's two nameservers are both offline.
> 
> Digging a little deeper, the IPs of vn.al's nameservers aren't even being advertised on the internet right now. For example, Hurricane Electric's looking glass:
> 
> ```
> core2.abq1.he.net> show ip bgp routes detail 66.59.198.225 
>   BGP4 : None of the BGP4 routes match the display condition
> ```
> 
> Cogent's looking glass:
> 
> ```
> Tue Sep  5 06:14:59.399 UTC
> % Network not in table
> ```
> 
> Without further information, it seems to me the project/organization is defunct, and this PR can be closed as obsolete.

Agreed.   @vnddns can re-open this should things open back up

2023-09-05 06:40 UTC, closed without merging

2023-09-06 04:46 UTC, vnddns commented
There was a problem in our data backup server system so the system was temporarily inaccessible but everything has been resolved. Please consider helping us. Thank you very much.