Update public_suffix_list.dat
publicsuffix/list pull request #1565
Opened 2022-05-08 12:27 UTC by ghostzero

* [x] Description of Organization
* [ ] Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place

__Submitter affirms the following:__ 

  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
  * [ ] This request was _not_ submitted with the objective of working around other third-party limits

  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting

---
__For Private section requests that are submitting entries for domains that match their organization website's primary domain:__

``` 
Seriously, carefully read the downline flow of the PSL and the 
guidelines. Your request could very likely alter the cookie and 
certificate (as well as other) behaviours on your core domain name in 
ways that could be problematic for your business.

Rollback is really not predicatable, as those who use or incorporate 
the PSL do what they do, and when. It is not within the PSL volunteers' 
control to do anything about that.  

The volunteers are busy with new requests, and rollbacks are lowest 
priority, so if something gets broken by your PR, it will potentially 
stay that way for an indefinitely long while.
```
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

DNS Verification via dig
=======

make test
=========

2022-05-08 18:40 UTC, Dygear commented
Will update the domain's expiration date. I've been meaning to register it for the max duration as it also helps with Google Results. Will comment back when done.

2022-05-09 02:22 UTC, Dygear commented
Done. Apparently max is 9 years.

2022-05-12 17:35 UTC, ghostzero commented
Updated description of organisation and ran tests successfully on my branch. Also asked every domain owner to extend their domains so they have at least two years on record.

2022-05-12 17:41 UTC, ghostzero commented
Added missing domain, tests still passing.

2022-05-25 10:39 UTC, ghostzero commented
@dnsguru Hello, the PR is not no longer in draft and waiting to be reviewed. Thanks!

2022-10-13 20:35 UTC, ghostzero commented
@dnsguru I kindly ask you to review this PR. Thanks!

2023-04-07 14:11 UTC, ghostzero commented
Hi, what is the status here? Would be great if we get our domains in the psl so I can make our domains re-available for the public.

2024-01-31 08:00 UTC, simon-friedberger commented
If this is still required, please update the PR.

2024-02-05 02:31 UTC, Dygear commented
I have renewed the domain for like 8+ years, so it should be ok now.

2024-02-05 05:20 UTC, dnsguru commented
Please work directly with Cloudflare and Let's Encrypt on lifting their limits for you.  Adding them here as a workaround is not the reason the PSL exists.

2024-02-05 05:37 UTC, dnsguru commented
>We want services like Cloudflare & Let's Encrypt to accept our domains as eTLDs, so that restrictions are lifted. In other words, it should be allowed to register a domain like example.ts.io on Cloudflare and rate limits of aaa.ts.io should not affect bbb.ts.io on Let's Encrypt.

[OUR GUIDELINES ON SUBMISSIONS](https://github.com/publicsuffix/list/wiki/Third-Party-Diffusion)

[LE RATE INCREASE FORM TO ASK DIRECTLY](https://isrg.formstack.com/forms/rate_limit_adjustment_request)

2024-02-05 10:48 UTC, simon-friedberger requested changes
* [ ] Expiration
  * [ ] bitinflow.space expires 2025-01-06
  * [ ] maid.build expires 2024-05-05
  * [x] ts.io expires 2033-02-06
* [ ] DNS _psl entries
* [x] Tests pass
* [x] Sorting according to guidelines
* [ ] Reasoning/Organization description

2024-02-05 10:48 UTC, simon-friedberger commented on public_suffix_list.dat
> +// Submitted by René Preuß <rene@bitinflow.com>
If possible, please provide a non-personal address.

2024-02-05 10:48 UTC, simon-friedberger commented
Please add a number of customers to the PR description.

2024-03-20 07:45 UTC, closed without merging