Add gitee.io
publicsuffix/list pull request #1728
Opened 2023-04-03 03:32 UTC by liminghua999

Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [ ] Description of Organization
* [ ] Robust Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [ ] This request was _not_ submitted with the objective of working around other third-party limits

  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: 

Reason for PSL Inclusion
====

Number of users this request is being made to serve:

DNS Verification via dig
=======

Results of Syntax Checker (`make test`)
=========

2023-04-03 14:43 UTC, dnsguru requested changes
Please remove the extra newline 12196

2023-04-04 17:34 UTC, dnsguru commented
> > Please remove the extra newline 12196
> 
> done

Excellent.  And now... patience.  This project is maintained by volunteers and we are just getting to requests from April of last year.

2024-02-05 16:33 UTC, simon-friedberger requested changes
* [ ] Expiration (Note: Must STAY above 2y at all times)
  * [ ] gitee.io expires 2025-02-10
* [x] DNS _psl entries
* [x] Tests pass
* [ ] Sorting
* [x] Reasoning/Organization description

2024-02-05 16:33 UTC, simon-friedberger commented on public_suffix_list.dat
> +// Gitee  : https://www.gitee.io
This should be sorted above Github.

2024-02-05 16:33 UTC, simon-friedberger commented on public_suffix_list.dat
> +// Submitted by LiMingHua <liminghua@oschina.net>
Please use a non-personal e-mail.

2024-03-27 16:28 UTC, closed without merging