Update public_suffix_list.dat
publicsuffix/list pull request #1795
Opened 2023-07-07 20:25 UTC by rezraf

Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [x] Description of Organization
* [x] Robust Reason for PSL Inclusion
* [x] DNS verification via dig
* [x] Run Syntax Checker (make test)

* [x] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [x] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [x] This request was _not_ submitted with the objective of working around other third-party limits

  * [x] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [x] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [x] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

We are planning to use aaa.vodka domain zone for our hosting clients and give them a subdomain instead of an IP address for their server

Organization Website: https://rezraf.com & https://panel.rezraf.com

Reason for PSL Inclusion
====

- We want to give out our personal subdomain to everyone
- We want to isolate cookies
- We want the ssl certificate to be unique for everyone, and not installed at the top of the domain

Number of users this request is being made to serve: 10k

DNS Verification via dig
=======

dig +short TXT _psl.aaa.vodka
"https://github.com/publicsuffix/list/pull/XXX"

Results of Syntax Checker (`make test`)
=========

All tests passed
<!--

2023-07-11 10:24 UTC, rezraf reviewed
edit site

2024-02-02 19:23 UTC, rezraf commented
@simon-friedberger We've changed the rationale

2024-02-05 11:16 UTC, rezraf commented
> rezraf.com returns 403

sorry, we transfered landing to protesian.host

2024-02-05 13:47 UTC, rezraf commented
> Please update the description!

ready

2024-02-05 14:26 UTC, simon-friedberger requested changes
Please add a bit more description of your organization to the PR since the website is in Russian.

* [ ] aaa.vodka expires 2025-07-07
* [x] DNS _psl entries
* [x] Tests pass
* [ ] Sorting
* [ ] Reasoning/Organization description

2024-02-05 14:26 UTC, simon-friedberger commented on public_suffix_list.dat
> +// Submitted by Kirill Rezraf <kirill@rezraf.com>
Please provide a non-personalized e-mail.

2024-02-05 14:26 UTC, simon-friedberger commented on public_suffix_list.dat
> +// AAA workspace : https://aaa.vodka
Sort this into the list by organization name.

2024-02-05 17:57 UTC, rezraf commented
@simon-friedberger is ready all, aaa.vodka expires 2027-07-07, email changed to email company and edited company description

2024-02-06 04:29 UTC, dnsguru commented
Wow. Tolstoy-GPT up in here

2024-03-26 21:10 UTC, rezraf commented
Hi, when should I expect approval? @simon-friedberger

2024-03-27 09:15 UTC, simon-friedberger commented
Merging is up to @dnsguru

2024-03-29 23:39 UTC, rezraf commented
@dnsguru Hello! Approximately how long will it take to merge? Thank you

2024-04-10 09:04 UTC, simon-friedberger requested changes

2024-04-10 09:04 UTC, simon-friedberger commented on public_suffix_list.dat
> +// Submitted by Kirill Rezraf <rezrafdonate@gmail.com>
Please depersonalize this.

2024-04-16 18:54 UTC, rezraf commented
@simon-friedberger i am fixed your request

2024-05-02 07:38 UTC, merged

2024-09-05 23:11 UTC, groundcat commented on public_suffix_list.dat
> +// Submitted by Kirill Rezraf <admin@aaa.vodka>
Hello @rezraf just a heads-up that the email address you left in the comment section is not valid, as the domain of your email address doesn't have MX records, so it won't be reachable if the PSL maintainers or volunteers try to contact you or your organization in the future. It's recommended to either fix the email account or submit an amendment to update it to a valid one. Thank you.