Update public_suffix_list.dat
publicsuffix/list pull request #1837
Opened 2023-08-28 08:48 UTC by qnapnickchang

add a new domain for our public dynamic dns service

Public Suffix List (PSL) Pull Request (PR) Template
====

Each PSL PR needs to have a description, rationale, indication of DNS validation and syntax checking, as well as a number of acknowledgements from the submitter.  This template must be included with each PR, and the submitting party MUST provide responses to all of the elements in order to be considered.

### Checklist of required steps

* [ ] Description of Organization
* [ ] Robust Reason for PSL Inclusion
* [ ] DNS verification via dig
* [ ] Run Syntax Checker (make test)

* [ ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section

__Submitter affirms the following:__ 

  * [ ] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)

  * [ ] This request was _not_ submitted with the objective of working around other third-party limits

  * [ ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
  * [ ] The submission follows the [guidelines](https://github.com/publicsuffix/list/wiki/Format) on formatting and sorting

---

For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take a long time to rollback, if at all.

To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding. 

PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or update.

(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))

 * [ ] *Yes, I understand*.  I could break my organization's website cookies etc. and the rollback timing, etc is acceptable.  *Proceed*.
---

Description of Organization
====

Organization Website: https://www.qnap.com
QNAP System Inc. is a corporation that specializes in Network-attached storage (NAS) appliances.

Reason for PSL Inclusion
====

Hello, I'm engineer from qnap.com and we would like to add a new domain for our public dynamic dns service. 
Number of users this request is being made to serve: 1,00k

DNS Verification via dig
=======

Results of Syntax Checker (`make test`)
=========

2024-03-07 09:38 UTC, simon-friedberger requested changes
Please fix the sorting. (The old entries are also wrong.) If you can, please add a non-personal e-mail.

2024-04-10 09:35 UTC, simon-friedberger commented
@qnapnickchang Any updates?

2024-04-10 09:53 UTC, qnapnickchang commented
Hi @simon-friedberger  fix soring. please check again. thanks

2024-04-10 10:47 UTC, simon-friedberger commented
* [ ] Expiration (Note: Must STAY >2y at all times)
  * [x] mycloudnas.com expires 2027-07-19
  * [ ] mynascloud.com expires 2025-08-19
  * [x] myqnapcloud.cn expires 2026-07-10
  * [ ] dev-myqnapcloud.com expires 2024-08-16
  * [x] alpha-myqnapcloud.com expires 2027-02-23
  * [x] myqnapcloud.com expires 2027-01-24
* [x] DNS _psl entries (Note: Must STAY in place)
  * [x] mycloudnas.com
  * [x] mynascloud.com
  * [x] myqnapcloud.cn
  * [x] dev-myqnapcloud.com
  * [x] alpha-myqnapcloud.com
  * [x] myqnapcloud.com
* [x] Tests pass
* [ ] Sorting
* [x] Reasoning/Organization description

2024-04-10 10:48 UTC, simon-friedberger commented
https://github.com/publicsuffix/list/wiki/Guidelines#sort-your-submission-correctly-important

2024-04-15 01:50 UTC, qnapnickchang commented
Hi @simon-friedberger 

- domain renew. Please check again.
- Fix soring 

Thanks

2024-04-15 11:49 UTC, simon-friedberger commented on public_suffix_list.dat
>  // Submitted by Nick Chang <nickchang@qnap.com>
Please use an address which isn't tied to a specific person.

2024-04-16 00:53 UTC, qnapnickchang commented
@simon-friedberger 
Updated. Please check again.

Thanks

2024-04-19 10:44 UTC, merged